### PR TITLE
Add favicon for page

### PR DESCRIPTION
**Pull request by katyalsahil1990**

### CODE REVIEW

**Comment by katyalsahil1990** [comment]
It resolved your issue..

**Comment by katyalsahil1990** [comment]
Its showing just do a hard refresh.

**Comment by mkc1000** [comment]
The file is in the repo, but when I go to the website, the image isn't in
the chrome tab. And on settings, it says the site has been published, so
it's not just a lag.

**Comment by katyalsahil1990** [comment]
image

**Comment by mkc1000** [comment]
The goal was not just for the file to be in the repo--it has to display on
the actual website! Sorry to have wasted your time. I didn't take the down
listing in time after someone already accepted the job. So I hope you think
it's fair that I not pay, since it didn't solve the issue, and I hope you
think it's fair if I don't ask you to complete the task, since someone else
is on it.

**Comment by katyalsahil1990** [comment]
I am not asking you to pay me. Because it's showing for me in each and every browser.
Screenshot 2020-06-21 at 4 15 56 PM

**Comment by mkc1000** [comment]
Yes that was the result of another commit by the person who accepted the
job.

**Comment by katyalsahil1990** [comment]
Thanks Man!!!!

**Pull request merged**
